dns:
  nameserver:
#   - 172.30.0.1
#   - dhcp://"eth3"
  - dhcp://"pppoe0"
  - 114.114.114.114
  - 119.29.29.29
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  # https://public-dns.info/nameserver/hk.html
  - 209.146.104.69
  - 223.255.177.202
  # https://github.com/dns-sb/DoH
  - https://doh.dns.sb/dns-query
  - https://doh.sb/dns-query
  - https://185.222.222.222/dns-query
  - https://45.11.45.11/dns-query
  # copy from openclash
  - https://dns.cloudflare.com/dns-query
  - "[2001:da8::666]:53"
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  #- "+.*"
  - "*.lan"
  - "+.local"
  - hikups
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - "+.cn"
  - time.*.com
  - time.*.gov
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "+.pool.ntp.org"
  - "+.sandai.net"
  - "+.xunlei.com"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "+.media.dssott.com"
  - "+.360buyimg.com"
  - "+.jd.com"
  - "+.autonavi.com"
  - "+.taobao.com"
  - "+.1688.com"
  - "+.alibabausercontent.com"
  - "+.alipay.com"
  - "+.alipayobjects.com"
  - "+.alicdn.com"
  - "+.weibo.com"
  - "+.weibocdn.com"
  - "+.qq.com"
  - "+.tencentmusic.com"
  - "+.qcloud.com"
  - "+.myqcloud.com"
  - "+.gtimg.com"
  - "+.gtdimg.com"
  - "+.smtcdns.com"
  - "+.cibntv.net"
  - "+.youku.com"
  - "+.ykimg.com"
  - "+.qy.net"
  - "+.iqiyi.com"
  - "+.iqiyipic.com"
  - "+.new1cloud.com"
  - "+.71edge.com"
  - "+.sogoucdn.com"
  - "+.umeng.com"
  - "+.umengcloud.com"
  - "+.bilibili.com"
  - "+.biliapi.net"
  - "+.biliapi.com"
  - "+.biligame.com"
  - "+.bilivideo.com"
  - "+.hdslb.com"
  - "+.163.com"
  - "+.163yun.com"
  - "+.126.com"
  - "+.126.net"
  - "+.127.net"
  - "+.mgtv.com"
  - "+.hunantv.com"
  - "+.hitv.com"
  - "+.miaozhen.com"
  default-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - "[2001:da8::666]:53"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
  nameserver-policy:
    '+.cn': '127.0.0.1'